spring:
  application:
    name: shipment-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:shipmenttracker}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    liquibase: DEBUG

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shipment-tracker
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8083
